
export const BlogsData=[
    {
        id: 1,
        image1: require('./App_assests/blog2.jpg'),
        tags: ['musical', 'Tutor', 'Playlist', 'Lifestyle'],
        user: {
          name: 'Mark wiens',
          date: '12 Dec, 2017',
          views: '1.2M Views',
          comments: '06 Comments',
        },
        image2: require('./App_assests/Blogs/blog1.jpg'),
        image3: require('./App_assests/Blogs/blog4.jpg'),
        title: 'Flute Concert at our land',
        mainexpert:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get comforted yourself at a fraction.',
        expert1: 'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get comforted yourself at a fraction.',
      expert2: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
     expert3: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
    expert4:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.',
    expert5:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.',
        link: 'blog-single.html',
      },
      {
        id: 2,
        tags: ['musical', 'Tutor', 'Playlist', 'Lifestyle'],
        user: {
          name: 'Mark wiens',
          date: '12 Dec, 2017',
          views: '1.2M Views',
          comments: '06 Comments',
        },
        image1: require('./App_assests/bh1.jpg'),
      image2: require('./App_assests/Blogs/bs3.jpg'),
      image3: require('./App_assests/Blogs/bs4.jpg'),
        title: 'Music Concert at Goa',
        mainexpert:'Attend the musical concert and avoid being an introvert and feel and the magic of music.',
        expert1: 'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get comforted yourself at a fraction.',
      expert2: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
     expert3: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
    expert4:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.',
    expert5:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.',
        link: 'blog-single2.html',
      },
      {
        id: 3,
        tags: ['musical', 'Tutor', 'Playlist', 'Lifestyle'],
        user: {
          name: 'Mark wiens',
          date: '12 Dec, 2017',
          views: '1.2M Views',
          comments: '06 Comments',
        },
        image1: require('./App_assests/bh2.jpg'),
    image2: require('./App_assests/Blogs/d1.jpg'),
    image3: require('./App_assests/Blogs/d3.jpg'),
        title: 'Drum show at music areana',
        mainexpert:'Get into the arena and feel the beats of the music sensation.',
         expert1: 'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get comforted yourself at a fraction.',
      expert2: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
     expert3: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
    expert4:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.',
    expert5:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.',
        link: 'blog-single3.html',
      },
      {
        id: 4,
        tags: ['musical', 'Tutor', 'Playlist', 'Lifestyle'],
        user: {
          name: 'Mark wiens',
          date: '12 Dec, 2017',
          views: '1.2M Views',
          comments: '06 Comments',
        },
        image1: require('./App_assests/bh3.jpg'),
        image2: require('./App_assests/Blogs/t3.jpg'),
        image3: require('./App_assests/Blogs/t1.jpg'),
        title: 'The Night Sky Trumpet show at hall of frames',
        mainexpert:'The Trumpet show of music sensation Nick was on the high at the hall of frames.',
         expert1: 'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get comforted yourself at a fraction.',
      expert2: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
     expert3: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
    expert4:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.',
    expert5:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.',
        link: 'blog-single4.html',
      },
      {
        id: 5,
        tags: ['musical', 'Tutor', 'Playlist', 'Lifestyle'],
        user: {
          name: 'Mark wiens',
          date: '12 Dec, 2017',
          views: '1.2M Views',
          comments: '06 Comments',
        },
        image1: require('./App_assests/bh4.jpg'),
    image2: require('./App_assests/Blogs/v1.jpg'),
    image3: require('./App_assests/Blogs/v3.jpg'),
        title: 'Shree Rudra vena live performance at mukund hall',
        mainexpert:'Majestic performance of the legen of Veena Rudra was great to hear it live.',
         expert1: 'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get comforted yourself at a fraction.',
      expert2: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
     expert3: 'Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training. who has the willpower to actually sit through a self-imposed.',
    expert4:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower to actually sit through a self-imposed MCSE training.',
    expert5:'MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money boot camp when you can get the MCSE study materials yourself at a fraction of the camp price. However, who has the willpower.',
        link: 'blog-single5.html',
      }
    
];
